spring:
  application:
    name: analog
    admin:
      enabled: true
  main:
    banner-mode: log
  jackson:
    # prevents Jackson mapper from serializing null values, empty arrays and false booleans
    default-property-inclusion: non_default
  mvc:
    # provides independence on language requested by client with Accept-Language HTTP header
    localeResolver: FIXED
  messages:
    # prevents AnaLog from using OS language as it may differ from the one selected in external application.yaml
    fallback-to-system-locale: false
server:
  servlet:
    application-display-name: AnaLog
logging:
  config: classpath:logging/logback-console.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

javamelody:
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: true
  advisor-auto-proxy-creator-enabled: false     # to prevent BeanNotOfRequiredTypeException when getting lazy services
  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests
    log: true
    # to exclude images, css, fonts and js urls from the monitoring:
    url-exclude-pattern: (/webjars/.*|.*\.css|.*\.js|/general/fonts/.*|.*\.png|.*\.jp[e]?g|.*\.gif|.*\.ico|.*\.htm[l]?)
    storage-directory: '${user.dir}/work/javamelody'
    # to add basic auth:
    #authorized-users: admin:pwd
    # to change the default storage directory:
    #storage-directory: /tmp/javamelody
    # to change the default "/monitoring" path
    #monitoring-path: /admin/performance

tracking:
  grouping:
    sizeThreshold: 500
    timeout: 500ms
  tailSize:
    flat: 45
    group: 20
  retryDelay: 5s

adapters:
  file:
    detectionRequest: 'tail --version'
    tailImplementations:
      GnuCoreUtils:        # both tail implementations: Linux native and Cygwin Windows port
        executable:        'tail'
        followCommand:     '-F -n {0}'
        detectionResponse: 'tail (GNU coreutils)'
      Mac:
        executable:        'tail'
        followCommand:     '-F -{0}'
        detectionResponse: 'tail: illegal option --'
      Solaris:
        executable:        'tail'
        followCommand:     '-{0}f'
        detectionResponse: 'usage: tail'
  docker:
    executable:     'sudo docker'
    followCommand:  'logs --follow --tail={0}'
    versionCommand: 'version --format ''{{.Client.Version}}'''
  kubernetes:
    executable:     'kubectl'
    followCommand:  'logs --follow --tail={0}'
    versionCommand: 'version --client --short'

# AnaLog uses restrictive access control model, i.e. everything that is not explicitly allowed, is denied.
# The following (default) settings allow access to certain common log locations. These settings can 
# be overridden by AnaLog administrator as needed via external 'application.yaml' file. 
allowed-log-locations:
  file:
    include:
      - ${user.home}/**.log         # any logs in current users home directory
      - ${user.dir}/**.log          # AnaLog's own logs
    exclude:
      - ${user.home}/**/.*          # exception for hidden files
    # - /home/me/audit.log          # just an example of concrete path       
    symlink-resolution-limit: 1
