spring:
  application:
    name: AnaLog
    admin:
      enabled: true

server:
  session:
    persistent: true
    cookie:
      max-age: 86400
  display-name: AnaLog

logging:
  level:
    root: INFO
    ru.ftc.upc.testing.analog: TRACE
    ru.ftc.upc.testing.analog.service.EncodingDetector: INFO
    ru.ftc.upc.testing.analog.remote.agent.misc.AddressAwareRmiOutboundGateway: INFO
    ru.ftc.upc.testing.analog.remote.agent.RecordAggregatorConfigurer: INFO
    ru.ftc.upc.testing.analog.util.dev.DevLogSource: INFO
    org.springframework.integration: INFO
    org.springframework.web.socket: DEBUG
    org.springframework.messaging.simp.stomp: TRACE
    org.springframework.messaging.simp.broker: DEBUG
    org.springframework.integration.file.tail.OSDelegatingFileTailingMessageProducer: TRACE
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

tracking:
  groupSizeThreshold: 50
  groupTimeoutMs: 1000