spring:
  application:
    name: AnaLog
    admin:
      enabled: true

server:
  session:
    persistent: true
    cookie:
      max-age: 86400
  display-name: AnaLog

logging:
  level:
    root: info
    ru.ftc.upc.testing.analog: DEBUG
    ru.ftc.upc.testing.analog.service.EncodingDetector: INFO
    org.springframework.integration: INFO