spring:
  application:
    name: analog
    admin:
      enabled: true
  main:
    banner-mode: log
  jackson:
    # prevents Jackson mapper from serializing null values, empty arrays and false booleans
    default-property-inclusion: non_default
server:
  servlet:
    application-display-name: AnaLog

javamelody:
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: true
  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests
    log: true
    # to exclude images, css, fonts and js urls from the monitoring:
    url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # to add basic auth:
    #authorized-users: admin:pwd
    # to change the default storage directory:
    #storage-directory: /tmp/javamelody
    # to change the default "/monitoring" path
    #monitoring-path: /admin/performance

tracking:
  group:
    sizeThreshold: 500
    timeoutMs: 500
