# Настройки подключения конечных пользователей:
server:
  port: 8080                # - этот порт должен быть указан в браузере;
  address: mycompany.com    # - имя/адрес хоста не обязательны; по умолчанию 0.0.0.0

# Список узлов, из которых состоит кластер АнаЛога (в том числе, если в нем всего один узел - текущий):
nodes:
  - name: primary                           # читабельное имя узла (для удобства обращения)
    host: mycompany.com                     # хост узла (без порта)
    agentPort: 7801                         # порт агента
    serverPort: 9090                        # порт сервера (тот же, что и server.port этого узла)
    myself: true                            # признак того, что этот узел является сервером (см. выше);
                                            # такой признак должен присутствовать только у одного (серверного) узла
  - name: backup-node                         # читабельное имя второго узла
    host: backup.mycompany.com                # хост второго узла (число узлов не ограничено)
    agentPort: 7801                           # порт агента
    # serverPort: 8080                        # если порт удаленного сервера равен server.port текущего, можно опустить


# Варианты выбора логов из UI:
choices:
  - group: MT                               # название группы вариантов (число групп не ограничено)
    pathBase: C:\lang\analog\log-samples\   # базовый путь логов в этой группе (добавляется к началу других путей)
    plainLogs:                              # список простых (одинарных) логов группы
      - core.log as "static $f - $g"
        # формат элемента списка: <fileNameOrPath>[ as "<alias>"[ (selected)]]
        # , где <fileNameOrPath> - полный либо относительный путь к файлу лога (в зависимости от наличия pathBase),
        # <alias> - отображаемое в UI имя лога в любом формате; поддерживаются подстановочные переменные:
        #         $f - имя и расширение файла лога, $g - имя группы (пример алиаса: "Тестовый $f - $g")
        # (selected) - статичный признак, указывающая на то, что данный вариант лога будет выбран по умолчанию
      - pppinfo.log as "$f - $g" (selected)
      - generated\core.log as "$f - $g aka generated"
    compositeLogs:                          # список композитных (составных) логов группы
      - path: generated\bankplus.log        # полный либо относительный путь к файлу лога (в зависимости от pathBase),
        timestamp: dd.MM.yy HH:mm:ss,SSS    # формат временной метки
        node: primary                       # имя узла, где лежит лог (по умолчанию: узел с myself=true)
        title: $f - $g                      # имя лога (формат см. выше)
        # selected: true                      # признак выбора по умолчанию (должен быть лишь один на все варианты)
        includes:                           # список других логов, входящих в состав композита
          - node: backup-node                           # путь к включаемому логу (только абсолютный!)
            path: /pub/home/me/logs/backup.log          # имя узла с логом (по умолчанию: узел с myself=true)
            timestamp: dd/MM/yy HH:mm:ss.SSS            # формат временной метки
    scanDir: C:\lang\analog\log-samples\to-scan   # полный путь к директории, все файлы которой должны автоматически
                                                  # стать вариантами выбора логов (не включая поддиректории)