server:
  port: 8080
#logging:
#  file: application.log

choices:
  - group: Логи UPC-1
    paths:
      - log-samples\bankplus.log
      - log-samples\logSample.log (selected by default)

  - group: Логи UPC-2
    paths:
      - log-samples/core.log
      - log-samples/pppinfo.log