server:
  port: 8080
jmx:
  rmi:
    host: localhost
    port: 1099

nodes:
  - name: angara
    host: angara.ftc.ru
    agentPort: 7801
    serverPort: 8080
    # myself: true
  - name: volga
    host: volga.ftc.ru
    agentPort: 7802
  - name: tobol
    host: tobol.ftc.ru
    agentPort: 7803

recordLevels:
  - TRACE
  - DEBUG
  - INFO
  - WARN
  - ERROR
  - FATAL

choices:
  - group: MT
    pathBase: C:\lang\analog\log-samples\
    plainLogs:
      - core.log as "static $f - $g"
      - pppinfo.log as "$f - $g"
      - generated\core.log as "generated $f - $g"
    compositeLogs:
      - path: generated\bankplus.log
        node: angara
        title: $f - $g
        selected: true
        encoding: CP-1251
        timestamp: dd.MM.yy HH:mm:ss,SSS
        includes:
          - path: C:\lang\analog\log-samples\generated\core.log
            node: angara
            timestamp: yyyy-MM-dd HH:mm:ss,SSS # 2017-11-09 22:31:03,084
          - node: volga
            path: C:\lang\analog\log-samples\cluster\composite.log
            timestamp: dd.MM.yy HH:mm:ss,SSS
          - node: volga
            path: C:\lang\analog\log-samples\cluster\composite-2.log
            timestamp: dd.MM.yy HH:mm:ss,SSS

  - group: Микросервисы
    pathBase: C:\lang\analog\log-samples\
    plainLogs:
      - cluster/static-source.log as "$f - $g"
      - core-all.log as "$f - $g"
      - cluster\composite.log as "$f (plain)"
    compositeLogs:
      - path: bankplus.log
        node: volga
        title: $f - $g
        timestamp: dd.MM.yy HH:mm:ss,SSS
      - path: logSample.log
        node: tobol
        title: $f - $g
        timestamp: dd.MM.yy HH:mm:ss,SSS
