server:
    port: 8083
    address: 0.0.0.0

nodes:
  this:
    name: myself
    agentPort: 7801

adapters:
  docker:
    useSudo: true

choices:
  - group: АнаЛог
    plainLogs:
      - path: ${user.dir}/log/${spring.application.name}.log
        title: 'Логи АнаЛога :-)'