server:
  port: 8083
  address: localhost
spring:
  mvc:
    locale: en    # as of v0.12 supported locales are: en, ru

nodes:
  this:
    name: myself
    agentPort: 7801

choices:
  - group: АнаЛог
    plainLogs:
      - path: ${user.dir}/log/${spring.application.name}.log
        title: 'Логи АнаЛога :-)'