server:
  port: 8080
#logging:
#  file: application.log

choices:
  - group: Логи UPC-1
    pathBase: C:\lang\analog\log-samples\
    paths:
      - sftp/logSample.log as "Примерчик ($F)"

  - group: Логи в CP1251
#    encoding: CP-1251
    paths:
      - log-samples/bankplus.log as "$g - $f" (selected)

  - group: Логи UPC-2
    paths:
      - C:\lang\analog\log-samples\core.log AS "Ядро ПК-2 ($f)"
      - log-samples/sftp/pppinfo.log

  - group: JavaScript
    scanDir: C:\lang\analog\src\main\resources\static\js
    paths:
      - C:\lang\analog\src\main\resources\static\js\main-controller.js as "Main.JS"