server:
  port: 8080
#logging:
#  file: application.log

choices:
  - group: Логи UPC-1
    pathBase: C:\lang\analog\log-samples\
    paths:
      - bankplus.log as "$g - $f"
      - logSample.log as "Примерчик ($F)" (selected)

  - group: Логи UPC-2
    paths:
      - C:\lang\analog\log-samples\core.log AS "Ядро ПК-2 ($f)"
      - C:/lang/analog/log-samples/pppinfo.log
