server:
    port: 8083
    address: 0.0.0.0

nodes:
  - name: myself
    host: localhost
    agentPort: 8085
    myself: true

choices:
  - group: АнаЛог
    plainLogs:
      - ${user.dir}/log/${spring.application.name}.log as "Логи АнаЛога :-)" (selected)
