server:
  port: 8080
#logging:
#  file: application.log

choices:
  - group: Логи UPC-1
    base: log-samples/
    paths:
      - bankplus.log as "$g - $f"
      - logSample.log as "Примерчик ($F)" (selected)

  - group: Логи UPC-2
    paths:
      - log-samples/core.log AS "Ядро ПК-2 ($f)"
      - log-samples/pppinfo.log
