server:
  port: 8080
#logging:
#  file: application.log

clusterNodes:
  - name: angara
    address: angara.ftc.ru:7801
    # myself: true
  - name: volga
    address: volga.ftc.ru:7802
  - name: tobol
    address: tobol.ftc.ru:7803

choices:
  - group: Samples
    pathBase: C:\lang\analog\log-samples\
    logs:
      - path: bankplus.log
        title: $g - $f
        selected: false
        encoding: CP-1251
        timestamp: dd.MM.yy HH:mm:ss,SSS

      - path: logSample.log
        title: $g - $f
        selected: false
        timestamp: dd.MM.yy HH:mm:ss,SSS

      - path: cluster\local\growing.log
        node: angara
        title: $g - $f
        selected: true
        encoding: CP-1251
        timestamp: dd.MM.yy HH:mm:ss,SSS
#        includes:
#          - node: angara
#            path: C:\lang\analog\log-samples\cluster\local\growing.log
#            timestamp: dd.MM.yy HH:mm:ss,SSS
