server:
  port: 8080
jmx:
  rmi:
    host: localhost
    port: 1099

clusterNodes:
  - name: angara
    address: angara.ftc.ru:7801
    # myself: true
  - name: volga
    address: volga.ftc.ru:7802
  - name: tobol
    address: tobol.ftc.ru:7803

choices:
  - group: MT
    pathBase: C:\lang\analog\log-samples\
    plainLogs:
      - core.log as "$f - $g"
      - pppinfo.log as "$f - $g"
    compositeLogs:
      - path: generated\bankplus.log
        node: angara
        title: $f - $g
        selected: true
        encoding: CP-1251
        timestamp: dd.MM.yy HH:mm:ss,SSS
        includes:
          - path: C:\lang\analog\log-samples\generated\core.log
            node: angara
            timestamp: yyyy-MM-dd HH:mm:ss,SSS # 2017-11-09 22:31:03,084
#          - node: tobol
#            path: C:\lang\analog\log-samples\cluster\composite.log
#            timestamp: dd.MM.yy HH:mm:ss,SSS

  - group: Микросервисы
    pathBase: C:\lang\analog\log-samples\
    plainLogs:
      - cluster/static-source.log as "$f - $g"
      - core-all.log as "$f - $g"
      - cluster\composite.log as "$f (plain)"
    compositeLogs:
      - path: bankplus.log
        title: $f - $g
        selected: false
        encoding: CP-1251
        timestamp: dd.MM.yy HH:mm:ss,SSS
      - path: logSample.log
        title: $f - $g
        selected: false
        timestamp: dd.MM.yy HH:mm:ss,SSS
