choices:
  - group: Примеры
    localPlainLogsBase: E:\Issues\Testing\incubator\analog\log-samples
    plainLogs:
      - path: generated\core.log
        title: $f (генерируемый)
      - path: generated\micro.log
      - path: source\core-source.log
      - path: source\micro-source.log
    compositeLogs:
      - title: 'Пробный композит'
        uriName: 'test-composite'
        includes:
          - path: E:\Issues\Testing\incubator\analog\log-samples\generated\core.log
            timestamp: yyyy-MM-dd HH:mm:ss.SSS
          - path: E:\Issues\Testing\incubator\analog\log-samples\generated\micro.log
            timestamp: yyyy-MM-dd HH:mm:ss,SSS
